; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = mk2

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
;platform = espressif32 @ 6.12.0
framework = arduino
build_unflags = -std=gnu++2a -std=gnu++2b -Werror=reorder
build_flags =
    -std=gnu++20
    -mtext-section-literals
build_src_flags =
    -Wall
    -Werror
    -DUSE_WIFI=1

lib_deps =
    EEPROM
    etlcpp/Embedded Template Library @ 20.47 ; 20.48 needs changes to bit_stream_writer
    tzapu/WiFiManager @ ^2.0.17
    ESP32Async/AsyncTCP @ ^3.4.10
;    https://github.com/mrrwa/LocoNet2.git#dcfad32
    https://github.com/positron96/LocoNet2.git#2f4fdc4
    olikraus/U8g2 @ ^2.36.18

monitor_filters = esp32_exception_decoder
monitor_speed = 115200


[env:mk1]
; old PCB from ~2021 using Lolin32 and L298N
board = lolin32
board_build.partitions = no_ota.csv  ; no plans for OTA anyway, so just reclaim some space
build_flags =
    ${env.build_flags}
    -DPCB_MK1

[env:mk2]
; new PCB from 2026 using ESP32 DevKit-C and TI's DRV8251's, OLED display.
board = esp32dev
board_build.partitions = no_ota.csv  ; no plans for OTA anyway, so just reclaim some space
build_flags =
    ${env.build_flags}
    -DPCB_MK2
    -DUSE_DISPLAY=1

;[env:native]
;platform = native
;lib_ignore =
;build_flags = -Ilib/DCC

;test_src_filter =
    ;+<../lib/DCC/LocoAddress.cpp>
