; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin32

[env]
build_unflags = -std=gnu++2a -std=gnu++2b -Werror=reorder
build_flags =
    -std=gnu++20
    -mtext-section-literals
build_src_flags =
    -Wall
    -Werror
    -DUSE_DISPLAY=0

[env:lolin32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
;platform = espressif32 @ 6.12.0
board = lolin32
framework = arduino
board_build.partitions = no_ota.csv  ; no plans for OTA anyway, so just reclaim some space

lib_deps =
    EEPROM
    etlcpp/Embedded Template Library @ ^20.47
    tzapu/WiFiManager @ ^2.0.17
    ESP32Async/AsyncTCP @ ^3.4.10
;    https://github.com/mrrwa/LocoNet2.git#dcfad32
    https://github.com/positron96/LocoNet2.git#ed9ba00
    olikraus/U8g2 @ ^2.36.18


; PIO seems to select port automatically.
;upload_port = COM8
;monitor_port = COM8

monitor_filters = esp32_exception_decoder
monitor_speed = 115200

[env:native]
platform = native
;lib_ignore =
;build_flags = -Ilib/DCC

;test_src_filter =
    ;+<../lib/DCC/LocoAddress.cpp>
